services:
  - type: web
    name: browser-bot-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.x
    autoDeploy: true 